#!/bin/sh

CERT_NAME=${CERT_NAME:-cert}
SUBJ_C=${OPENSSL_SUBJ_C:-}
SUBJ_ST=${OPENSSL_SUBJ_ST:-}
SUBJ_L=${OPENSSL_SUBJ_L:-}
SUBJ_O=${OPENSSL_SUBJ_O:-}
SUBJ_OU=${OPENSSL_SUBJ_OU:-}
SUBJ_CN=${OPENSSL_SUBJ_CN:-localhost}

persist_cert_dir=$(pwd)

cert_keyout="$CERT_NAME.key"
cert_out="$CERT_NAME.crt"

if [ ! -f "$persist_cert_dir/$cert_keyout" ] || [ ! -f "$persist_cert_dir/$cert_out" ]; then
    openssl req \
        -x509 \
        -nodes \
        -days ${OPENSSL_DAYS:-365} \
        -newkey ${OPENSSL_NEWKEY:-rsa:2048} \
        -keyout "$persist_cert_dir/$cert_keyout" \
        -out "$persist_cert_dir/$cert_out" \
        -subj "/C=$SUBJ_C/ST=$SUBJ_ST/L=$SUBJ_L/O=$SUBJ_O/OU=$SUBJ_OU/CN=$SUBJ_CN"
fi

# exec docker command
exec "$@"
